version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - npm ci
  build:
    on-failure: ABORT
    commands:
      # Build Website
      - cd site/
      - npx eleventy
artifacts:
  files:
    - '**/*'